import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import vm from "node:vm";
const require = createRequire(import.meta.url);
const adminRequire = createRequire(new URL("../../backend/admin/package.json", import.meta.url));
const vue = adminRequire("vue");
const ts = require("typescript");
const testModule = { exports: {}, require: () => vue };
vm.runInNewContext(ts.transpileModule(readFileSync(new URL("../../backend/admin/src/lib/use-local-pagination.ts", import.meta.url), "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, testModule);
test("admin paging selects ranges, resets sizes and clamps deleted last pages", async () => {
  const rows = vue.ref(Array.from({ length: 71 }, (_, i) => i));
  const pages = testModule.exports.useLocalPagination(rows);
  assert.equal(pages.pageItems.value.length, 20);
  pages.pagination.currentPage = 3;
  assert.equal(pages.pageItems.value[0], 40);
  pages.handlePageSizeChange(40);
  assert.equal(pages.pagination.currentPage, 1);
  assert.equal(pages.pageItems.value.length, 40);
  pages.pagination.currentPage = 2;
  rows.value = rows.value.slice(0, 12);
  await vue.nextTick();
  assert.equal(pages.pagination.currentPage, 1);
  assert.equal(pages.showPagination.value, false);
  rows.value = [];
  await vue.nextTick();
  assert.equal(pages.pageItems.value.length, 0);
  assert.equal(pages.pagination.currentPage, 1);
});
